# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f205638c63f9a69163c2422361ccca19ef2bb1aa000d392cb1ea3e90f2e61f2eaf397f9316db0ea45fa31059890c7c5193ff346132926e719985d4c13090f8

test:
  secret_key_base: 3cda855677191ba0e4936fdb490db28a5bf630ec31c15c79c251ba28ea5b3c05ec4746c999d356efd090fd6779273d4049f3c94534e62cb47acb56bfb42df302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
