# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b13edff607e21b559aa2c0bc931c62d0affe1fca43497b67a1c9581240703d3aa45ec715cb1d700de04647c3b298e01b9b7e011bee36c11e1a108c4256d489b1

test:
  secret_key_base: 4de5663d4cdc3391daeb3a5a789974328f53eab77e8379985eeb0725687b74a9e0608052ff85aad382df7427df6d06114349f4b756f46a15afcb04cb546c41ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
