# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eca7ce9999c481459d616db002292ac87a5054b9d6170ffdc0316f06acb68fca3a44145ad57333208072b0ce341afed2924bd0e04c6abd305ba1fceda8f44b34

test:
  secret_key_base: ed55e4bc59343d28a62f66b5cbb6db8fe85114f6e618cf0a486fd088f86fcceb7a456558f57dcac4209dd967e49e56e1fc439a34b1827509ffbe167c79e03968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
