# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23141b56864840f5bcd7255aba00ac6f85d036196636048e2b82bc76cd43e5a92e33784fe1ea105046e4986419b9baa772a87428bb60b265eb34af3bbe109505

test:
  secret_key_base: 9d33ceec8bd0171a2db2586f053ac1f0e3c8c818ece15e085d2a69b3154505087476354020c3a5415197fb437e682ad2ca08a3d9e43127260729370b10777a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
